// Write a source file back, with the checks that make a whole-file rewrite
// safe to perform without having watched the file the whole time.
//
// The only write mode is whole-file: there is no patch. That makes the write
// itself the easy part and everything around it the point —
//
//   - a checksum precondition, so a rewrite built from a stale copy is
//     refused instead of silently discarding whoever edited in between
//   - a dry run reporting which destinations the write would re-render
//   - advisories naming a file that is GENERATED or answers to an external
//     spec, which a caller must not edit blind
//   - siblings that could render to the same destination
//   - containment, so a relative path from a form or a request body cannot
//     write outside the collection folder
//
// An editing agent gets these through mikser-io-mcp. An application driving
// mikser as a CMS writes its own files and gets none of them, which is the
// gap this closes: the safety belongs to the write, not to one transport.

import path from 'node:path'
import { readdir } from 'node:fs/promises'

import runtime from './runtime.js'
import { readEntity, findEntities } from './catalog.js'
import { useCollection, checksum, readEntityContent, lookupKeys } from './utils.js'
import { nextCycleId, whenCycleCompletes } from './report.js'
import { recordChangeSetWrite, currentChangeSet } from './changeset.js'

// How far into a file to look for a marker. A header nobody reads is not a
// header; one buried 200 lines down is not either.
const HEADER_SCAN_LINES = 40

// Files a caller must not edit blind, read from the bytes themselves.
//
// Two kinds, kept apart because the instruction differs. `spec-locked` means
// the bytes answer to a document outside the repo — change it and the site
// stops matching something a human signed off. `generated` means editing the
// file is pointless, because the next build overwrites it.
const HEADER_PATTERNS = [
    { kind: 'spec-locked', re: /^\W*spec source:\s*(.+?)\s*$/i },
    { kind: 'generated',   re: /^\W*(?:generated by|do not edit)\b:?\s*(.*?)\s*$/i },
]

export function contentAdvisories(entity, content) {
    const found = []
    const push = (kind, detail, via, line) => {
        if (found.some(a => a.kind === kind)) return
        found.push({ kind, detail: detail || null, via, ...(line ? { line } : {}) })
    }
    // Explicit meta wins: someone wrote it down as data, on purpose.
    if (entity?.meta?.specLocked) {
        push('spec-locked', typeof entity.meta.specLocked === 'string' ? entity.meta.specLocked : null, 'meta.specLocked')
    }
    if (entity?.meta?.generated) {
        push('generated', typeof entity.meta.generated === 'string' ? entity.meta.generated : null, 'meta.generated')
    }
    if (typeof content === 'string') {
        const lines = content.split('\n', HEADER_SCAN_LINES)
        for (let i = 0; i < lines.length; i++) {
            for (const { kind, re } of HEADER_PATTERNS) {
                const m = re.exec(lines[i])
                if (m) push(kind, m[1], 'header', i + 1)
            }
        }
    }
    return found
}

// One line of prose for a response that has to be read, not parsed.
export function advisoryWarning(advisories) {
    if (!advisories?.length) return null
    return advisories.map(a => a.kind === 'spec-locked'
        ? `SPEC-LOCKED: ${a.detail ?? 'this file answers to an external specification'}`
            + ' — changing it may break a signed-off design. Confirm against the spec before writing.'
        : `GENERATED: ${a.detail ?? 'this file is produced by the build'}`
            + ' — edit its source instead; the next build overwrites this.').join(' ')
}

// Files beside this one that differ only by extension.
//
// An empty `index.md` sitting next to a real `index.yml` renders to the same
// destination; whichever renders last wins and the other output is discarded.
// The destination is not known until the cycle runs, but the COLLIDING SHAPE
// is visible at write time, and the write is the cheapest moment to say so.
export async function siblingDestinations(folder, relativePath) {
    const dir = path.dirname(path.join(folder, relativePath))
    const base = path.basename(relativePath, path.extname(relativePath))
    try {
        const entries = await readdir(dir, { withFileTypes: true })
        return entries
            .filter(e => e.isFile()
                && path.basename(e.name, path.extname(e.name)) === base
                && e.name !== path.basename(relativePath))
            .map(e => ({
                path: path.join(path.dirname(relativePath), e.name),
                note: 'same name, different extension — may render to the same destination',
            }))
    } catch {
        return []
    }
}

// The checksum of a file, or null when there is nothing there. Not an error
// path: "does not exist yet" is the normal case for a create.
async function fileChecksum(uri) {
    try {
        return await checksum(uri)
    } catch {
        return null
    }
}

// The catalog entity written from this file, when there is one.
async function findEntityAtUri(uri) {
    if (!uri) return null
    const matches = await findEntities({ uri })
    return matches?.[0] ?? null
}

// Resolve a catalog id to the (collection, relativePath) pair a write needs.
//
// Taken from the entity rather than by splitting the id: the id prefix is
// `idPrefix ?? '/' + collection` and the extension may have been stripped, so
// splitting on the first segment is a guess that is usually right and
// silently wrong for any source configured either way.
export async function locateEntityFile(id) {
    const entity = await readEntity({ id })
    if (!entity) return { error: `No entity with id ${id}.` }
    if (!entity.collection) {
        return { error: `Entity ${id} has no collection, so its file location cannot be derived.` }
    }
    let folder
    try {
        folder = useCollection(runtime, entity.collection).folder
    } catch (err) {
        return { error: `Entity ${id} is in collection ${entity.collection}, which has no folder: ${err.message}` }
    }
    if (!entity.uri) {
        return { error: `Entity ${id} has no uri — it is synthetic (emitted by a plugin, not read from a file) `
            + 'and has no file to rewrite.' }
    }
    const relativePath = path.relative(folder, entity.uri)
    if (!relativePath || relativePath.startsWith('..') || path.isAbsolute(relativePath)) {
        return { error: `Entity ${id} lives at ${entity.uri}, outside its collection folder ${folder}.` }
    }
    return { collection: entity.collection, relativePath }
}

// Create or overwrite a source file inside a collection.
//
// Takes either `id` (an existing entity) or `collection` + `relativePath`.
// `content` is the COMPLETE file: anything omitted is deleted.
//
// Never throws for an expected outcome. A refusal — a bad id, a path that
// escapes the collection, a checksum that no longer matches — comes back as
// `{ ok: false, refused }` with the facts needed to retry, because those are
// answers rather than faults.
//
//   dryRun      write nothing; report what the write would touch
//   ifChecksum  only write if the file's current DISK checksum equals this
//   awaitCycle  resolve once the cycle that picks the write up has finished,
//               with its build report attached
export async function writeEntitySource({
    id,
    collection,
    relativePath,
    content = '',
    ifChecksum,
    dryRun = false,
    awaitCycle = false,
    changeSet,
    summary,
    principal,
} = {}) {
    // An explicit id wins; otherwise inherit whatever set is in effect, so the
    // response can name the set a caller would undo even when the caller never
    // passed one.
    const ambient = currentChangeSet()
    changeSet ??= ambient?.changeSet
    summary ??= ambient?.summary
    principal ??= ambient?.principal

    if (id) {
        const located = await locateEntityFile(id)
        if (located.error) return { ok: false, refused: 'unresolvable-id', error: located.error }
        // An explicit pair still wins if a caller passes both, but disagreeing
        // with the id is a mistake worth refusing rather than silently
        // resolving one way.
        if (collection && collection !== located.collection) {
            return {
                ok: false,
                refused: 'collection-mismatch',
                error: `id ${id} is in collection ${located.collection}, not ${collection}. Pass one or the other.`,
            }
        }
        collection ??= located.collection
        relativePath ??= located.relativePath
    }
    if (!collection || !relativePath) {
        return {
            ok: false,
            refused: 'incomplete-target',
            error: 'Pass either `id` (for an existing entity) or both `collection` and `relativePath`.',
        }
    }

    let handle
    let uri
    try {
        handle = useCollection(runtime, collection)
        // Containment before anything reads or writes. A relative path that
        // escapes the collection must not even be STATTED — reporting a
        // checksum for /etc/passwd is a disclosure on its own.
        uri = handle.resolveWithin(relativePath)
    } catch (err) {
        return { ok: false, refused: 'invalid-target', collection, relativePath, error: err.message }
    }

    // Everything a caller should know BEFORE the bytes move. Computed for the
    // dry run and the real write alike, so the preview and the thing it
    // previews cannot disagree.
    const existing = id ? await readEntity({ id }) : await findEntityAtUri(uri)
    const onDisk = await readEntityContent({ uri }, { reload: true })
    const advisories = contentAdvisories(existing, typeof onDisk.content === 'string' ? onDisk.content : null)

    if (dryRun) {
        const wouldAffect = existing?.id ? (runtime.manifest?.affectedBy?.(existing) ?? []) : []
        const touched = new Set(wouldAffect.map(a => a.destination))
        return {
            ok: true, dryRun: true, collection, relativePath,
            id: existing?.id ?? null,
            exists: existing != null,
            currentChecksum: await fileChecksum(uri),
            advisories,
            warning: advisoryWarning(advisories),
            wouldAffect,
            wouldAffectCount: wouldAffect.length,
            siblingDestinations: await siblingDestinations(handle.folder, relativePath),
            // Collisions ALREADY standing at the outputs this write would
            // touch. A write cannot be blamed for them, but re-rendering into
            // one is how the wrong half of a contested destination wins.
            collisionsAtAffected: (runtime.manifest?.collisions?.() ?? [])
                .filter(c => touched.has(c.destination)),
            note: existing?.id
                ? 'Destinations are computed with the engine\'s own skip rule, so they match what a real cycle '
                    + 'would do — EXCEPT for changes to the entity\'s own frontmatter, which is parsed during '
                    + 'import and can move its destination.'
                : 'This file is not in the catalog yet, so nothing depends on it and there is no blast radius '
                    + 'to report.',
        }
    }

    // Checked immediately before the write. Not a lock — a writer that lands
    // between the check and the write still wins — but it closes the window
    // that matters in practice: read, think, write back a whole file built
    // from a copy that is now stale.
    const before = await fileChecksum(uri)
    if (ifChecksum !== undefined && ifChecksum !== before) {
        return {
            ok: false,
            refused: 'checksum-mismatch',
            collection, relativePath,
            expectedChecksum: ifChecksum,
            currentChecksum: before,
            hint: before === null
                ? 'The file does not exist. Omit ifChecksum to create it.'
                : 'The file on disk changed since you read it. Re-read it for the CONTENT, re-apply your change, '
                    + 'and retry with `currentChecksum` from THIS response.',
        }
    }

    const cycleId = nextCycleId()
    await handle.write(relativePath, content)

    // AFTER the write, so a set only ever claims paths that actually moved.
    // Claiming on intent would make a failed write undoable, and undoing a
    // write that never happened is a way to delete someone else's file.
    if (changeSet) recordChangeSetWrite({ changeSet, summary, principal, uri })

    const result = {
        ok: true, collection, relativePath,
        checksum: await fileChecksum(uri),
        bytes: Buffer.byteLength(content),
        cycleId,
        ...(changeSet ? { changeSet } : {}),
        siblingDestinations: await siblingDestinations(handle.folder, relativePath),
    }
    // Echoed on the way out, not only on read. A caller that never read the
    // file — or read past the header — is exactly the one that needs telling,
    // and telling it after the write still names what to check before deploy.
    if (advisories.length) {
        result.advisories = advisories
        result.warning = advisoryWarning(advisories)
    }
    if (awaitCycle) result.report = await whenCycleCompletes(cycleId)
    return result
}

// Remove a source file, with the same checks the write has plus the one that
// only matters for removal: what still points at it.
//
// Delete is the more destructive operation and had the fewest guards — no
// precondition, no preview, no advisory, and nothing at all about the
// references that break when an entity other documents point at disappears.
//
// Same contract as writeEntitySource: never throws for an expected outcome.
export async function deleteEntitySource({
    id,
    collection,
    relativePath,
    ifChecksum,
    dryRun = false,
    changeSet,
    summary,
    principal,
} = {}) {
    // An explicit id wins; otherwise inherit whatever set is in effect, so the
    // response can name the set a caller would undo even when the caller never
    // passed one.
    const ambient = currentChangeSet()
    changeSet ??= ambient?.changeSet
    summary ??= ambient?.summary
    principal ??= ambient?.principal

    if (id) {
        const located = await locateEntityFile(id)
        if (located.error) return { ok: false, refused: 'unresolvable-id', error: located.error }
        if (collection && collection !== located.collection) {
            return {
                ok: false,
                refused: 'collection-mismatch',
                error: `id ${id} is in collection ${located.collection}, not ${collection}. Pass one or the other.`,
            }
        }
        collection ??= located.collection
        relativePath ??= located.relativePath
    }
    if (!collection || !relativePath) {
        return {
            ok: false,
            refused: 'incomplete-target',
            error: 'Pass either `id` (for an existing entity) or both `collection` and `relativePath`.',
        }
    }

    let handle
    let uri
    try {
        handle = useCollection(runtime, collection)
        uri = handle.resolveWithin(relativePath)
    } catch (err) {
        return { ok: false, refused: 'invalid-target', collection, relativePath, error: err.message }
    }

    const existing = id ? await readEntity({ id }) : await findEntityAtUri(uri)
    const currentChecksum = await fileChecksum(uri)
    if (currentChecksum === null) {
        return {
            ok: false, refused: 'not-found', collection, relativePath,
            error: 'Nothing on disk at that path.',
        }
    }

    // Everything that would be left pointing at nothing. Asked of the
    // reference index rather than of the text, so it sees a `$`-ref by served
    // path exactly the way invalidation does.
    const referencedBy = existing ? referrersOf(existing) : []
    const wouldAffect = existing?.id ? (runtime.manifest?.affectedBy?.(existing) ?? []) : []

    if (dryRun) {
        return {
            ok: true, dryRun: true, collection, relativePath,
            id: existing?.id ?? null,
            exists: true,
            currentChecksum,
            referencedBy,
            wouldAffect,
            wouldAffectCount: wouldAffect.length,
            ...(referencedBy.length ? {
                warning: `${referencedBy.length} entit${referencedBy.length === 1 ? 'y' : 'ies'} reference this. `
                    + 'Deleting it leaves those references pointing at nothing.',
            } : {}),
        }
    }

    if (ifChecksum !== undefined && ifChecksum !== currentChecksum) {
        return {
            ok: false,
            refused: 'checksum-mismatch',
            collection, relativePath,
            expectedChecksum: ifChecksum,
            currentChecksum,
            hint: 'The file changed since you read it. Re-read it before deciding to delete it, and retry with '
                + '`currentChecksum` from THIS response.',
        }
    }

    await handle.remove(relativePath)
    if (changeSet) recordChangeSetWrite({ changeSet, summary, principal, uri, operation: 'delete' })

    return {
        ok: true, collection, relativePath,
        id: existing?.id ?? null,
        deletedChecksum: currentChecksum,
        cycleId: nextCycleId(),
        ...(changeSet ? { changeSet } : {}),
        referencedBy,
        ...(referencedBy.length ? {
            warning: `${referencedBy.length} entit${referencedBy.length === 1 ? 'y' : 'ies'} still reference this.`,
        } : {}),
    }
}

// Who points at this entity, by any of the keys it can be referenced by.
//
// `lookupKeys` rather than the id alone: content refers to served paths far
// more often than to catalog ids, and asking only about the id would report a
// widely-linked image as unreferenced.
function referrersOf(entity) {
    const refs = runtime.refs
    if (!refs?.inboundFor) return []
    const found = new Map()
    for (const key of [entity.id, ...(lookupKeys(entity) ?? [])]) {
        if (!key) continue
        let inbound = []
        try { inbound = refs.inboundFor(key) ?? [] } catch { continue }
        for (const ref of inbound) {
            if (!ref?.id || ref.id === entity.id) continue
            found.set(ref.id, { id: ref.id, ...(ref.field ? { field: ref.field } : {}) })
        }
    }
    return [...found.values()]
}
